### ISSUE TITLE
Publish a version to attach a Zenodo DOI

### ISSUE THREAD

**Issue by roxyboy** [bderembl/msom#12]
I think it would be beneficial to release a public version and have a [Zenodo DOI](https://zenodo.org/) for this `msom` package so that people including me can cite it.

**Comment by bderembl** [comment]
hopefully this worked: 
10.5281/zenodo.4669909

**Comment by roxyboy** [comment]
Awesome! Now you can put the Zenodo badge in the README.md :)

**Comment by bderembl** [comment]
I am not at that level of fanciness ... yet :)

**Comment by roxyboy** [comment]
I just made a PR to put the shiny badge ;)
