### ISSUE TITLE
Allow pickup files for passive tracers

### ISSUE THREAD

**Issue by roxyboy** [bderembl/msom#7]
I've been spinning up some seasonal runs but it would be nice to have the option to allow for a pickup file for passive tracers. I think this should be relatively straight forward; we would just need another file in addition to the relaxation file.

**Comment by bderembl** [comment]
There is already an option to restart a run with a given ptracer field: just put your ptracer file in the same directory as the executable an rename it as ptr0.bas. That should work. Let me know if it doesn't

**Comment by bderembl** [comment]
my bad, I see what you mean. it is better to add a relaxation file indeed

**Comment by roxyboy** [comment]
@bderembl Can you point me to where the initial condition for passive tracers (`ptr0.bas`) are read in `qg.h`? I'll try to make another PR.

**Comment by bderembl** [comment]
you need to delete these lines in qg.h
```
  if (nptr>0)
    list_copy_deep (ptracersl, ptr_relaxl, nl*nptr);
```
and in qg.c change

```
  if (nptr > 0){
    if ((fp = fopen("ptr0.bas", "r"))) {
      input_matrixl (ptracersl, fp);
      fclose(fp);
    } else {
      foreach() 
        for (scalar ptracers in ptracersl)
          ptracers[] = 1e-3*noise();
    }
    boundary(ptracersl);
  }
```
into
```
  if (nptr > 0){
    if ((fp = fopen("ptr0.bas", "r"))) {
      input_matrixl (ptracersl, fp);
      fclose(fp);
    } else {
      foreach() 
        for (scalar ptracers in ptracersl)
          ptracers[] = 1e-3*noise();
    }
    boundary(ptracersl);

    if ((fp = fopen("ptr_relax.bas", "r"))) {
      input_matrixl (ptr_relaxl, fp);
      fclose(fp);
    } 
  }
```
You will then have to provide a relaxation file 'ptr_relax.bas' along with an initial condition 'ptr0.bas'. If you don't provide a relaxation file, it will relax to zero

**Comment by bderembl** [comment]
done in PR#8
